import { type NextPage } from "next";
import Head from "next/head";

import Hero from "@/components/Sections/Hero";
import ApartCard from "@/components/Card/ApartCard";
import Layout from "@/components/Layout";

import { aparts } from "@/utils/data";

// import { api } from "@/utils/api";
// import Image from "next/image";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Avşa Apart</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <section className="container mx-auto mt-3 max-w-[1300px] rounded-md bg-white p-1">
          <div
            id="aparts_section"
            className="flex flex-col flex-wrap items-center justify-center gap-10 rounded-md border-[2px] border-dashed border-black/10 px-10 py-6 md:flex-row md:justify-between lg:gap-0"
          >
            {aparts.map((apart) => {
              return <ApartCard key={apart.id} {...apart} />;
            })}
          </div>
        </section>
      </Layout>
    </>
  );
};

export default Home;
