export const aparts = [
  {
    id: 1,
    title: 'Daire 1',
    description:
      'Dairelerimizde sizlerin rahatı için her şeyi düşündük. Evinizin konforunu aratmayacak bir tatil için tv, sıcak su ve her türlü mutfak araç gereci sizlerin hizmetine sunulmuştur. Avşa merkezde bulunan dairelerimiz Avşa İDO iskelesine 75 metre mesafededir. Ailenizle ve sevdiklerinizle güvenli, konforlu, hijyenik ve ekonomik bir tatil geçirmek için Avşa Mahir apart tüm sezon boyunca hizmetinizdedir.',
    features: [
      'Uydu Yayını',
      '24 Saat Sıcak Su',
      'Denize Yakın',
      'İDO İskelesine Yakın',
    ],
    coverImage: 'https://r.resimlink.com/hYrlE-Ak.jpg',
    images: [
      'https://r.resimlink.com/FfJVHM.jpg',
      'https://r.resimlink.com/HcQihYgGzUs.jpg',
      'https://r.resimlink.com/RBr-ow5.jpg',
      'https://r.resimlink.com/Tis8VOtrgFGK.jpg',
      'https://r.resimlink.com/hYrlE-Ak.jpg',
      'https://r.resimlink.com/bBsjhQA.jpg',
      'https://r.resimlink.com/ZHFGP.jpg',
      'https://r.resimlink.com/FUJM8d_0X.jpg',
      'https://r.resimlink.com/C32tvi.jpg',
      'https://r.resimlink.com/mzv_A.jpg',
    ],
    capacity: 5,
    size: 90,
    breakfast: false,
    terace: true,
    slug: 'apart-1',
  },
  {
    id: 2,
    title: 'Daire 2',
    description:
      'Dairelerimizde sizlerin rahatı için her şeyi düşündük. Evinizin konforunu aratmayacak bir tatil için tv, sıcak su ve her türlü mutfak araç gereci sizlerin hizmetine sunulmuştur. Avşa merkezde bulunan dairelerimiz Avşa İDO iskelesine 75 metre mesafededir. Ailenizle ve sevdiklerinizle güvenli, konforlu, hijyenik ve ekonomik bir tatil geçirmek için Avşa Mahir apart tüm sezon boyunca hizmetinizdedir.',
    features: [
      'Uydu Yayını',
      '24 Saat Sıcak Su',
      'Denize Yakın',
      'İDO İskelesine Yakın',
    ],
    coverImage:
      'https://r.resimlink.com/rm4KwzNCB.jpg?v=a2b5a4589c3d23790e492bb855d56158',
    images: [
      'https://r.resimlink.com/rm4KwzNCB.jpg?v=a2b5a4589c3d23790e492bb855d56158',
      'https://r.resimlink.com/Bikw529GqaA.jpg',
      'https://r.resimlink.com/eJ_zFZ9Pij4.jpg',
      'https://r.resimlink.com/V96INq5.jpg',
      'https://r.resimlink.com/2aLeKSYUtcXq.jpg',
      'https://r.resimlink.com/CYjSLkwH3eG.jpg',
      'https://r.resimlink.com/GgAb0.jpg',
      'https://r.resimlink.com/dImF5eAs_lTV.jpg',
      '/images/apart-images/apart2/video.mp4',
    ],
    capacity: 5,
    size: 75,
    breakfast: false,
    terace: true,
    slug: 'apart-2',
  },
  {
    id: 3,
    title: 'Daire 3',
    description:
      'Dairelerimizde sizlerin rahatı için her şeyi düşündük. Evinizin konforunu aratmayacak bir tatil için tv, sıcak su ve her türlü mutfak araç gereci sizlerin hizmetine sunulmuştur. Avşa merkezde bulunan dairelerimiz Avşa İDO iskelesine 75 metre mesafededir. Ailenizle ve sevdiklerinizle güvenli, konforlu, hijyenik ve ekonomik bir tatil geçirmek için Avşa Mahir apart tüm sezon boyunca hizmetinizdedir.',

    features: [
      'Uydu Yayını',
      '24 Saat Sıcak Su',
      'Denize Yakın',
      'İDO İskelesine Yakın',
    ],
    coverImage: 'https://r.resimlink.com/8i5kZxqpAsX.jpg',
    images: [
      'https://r.resimlink.com/XdJ2t.jpg',
      'https://r.resimlink.com/HhWZQITG9K.jpg',
      'https://r.resimlink.com/xbDdSkf1sX.jpg',
      'https://r.resimlink.com/Wo7lHp2.jpg',
      'https://r.resimlink.com/My75VdS0E4ZL.jpg',
      'https://r.resimlink.com/8i5kZxqpAsX.jpg',
      'https://r.resimlink.com/reR8F.jpg',
    ],
    capacity: 5,
    size: 50,
    breakfast: false,
    terace: false,
    slug: 'apart-3',
  },
];

export const gallery = [
  'https://r.resimlink.com/FfJVHM.jpg',
  'https://r.resimlink.com/HcQihYgGzUs.jpg',
  'https://r.resimlink.com/RBr-ow5.jpg',
  'https://r.resimlink.com/Tis8VOtrgFGK.jpg',
  'https://r.resimlink.com/hYrlE-Ak.jpg',
  'https://r.resimlink.com/bBsjhQA.jpg',
  'https://r.resimlink.com/ZHFGP.jpg',
  'https://r.resimlink.com/FUJM8d_0X.jpg',
  'https://r.resimlink.com/C32tvi.jpg',
  'https://r.resimlink.com/mzv_A.jpg',
  'https://r.resimlink.com/rm4KwzNCB.jpg',
  'https://r.resimlink.com/rm4KwzNCB.jpg',
  'https://r.resimlink.com/Bikw529GqaA.jpg',
  'https://r.resimlink.com/eJ_zFZ9Pij4.jpg',
  'https://r.resimlink.com/V96INq5.jpg',
  'https://r.resimlink.com/2aLeKSYUtcXq.jpg',
  'https://r.resimlink.com/CYjSLkwH3eG.jpg',
  'https://r.resimlink.com/GgAb0.jpg',
  'https://r.resimlink.com/dImF5eAs_lTV.jpg',
  'https://r.resimlink.com/XdJ2t.jpg',
  'https://r.resimlink.com/HhWZQITG9K.jpg',
  'https://r.resimlink.com/xbDdSkf1sX.jpg',
  'https://r.resimlink.com/Wo7lHp2.jpg',
  'https://r.resimlink.com/My75VdS0E4ZL.jpg',
  'https://r.resimlink.com/8i5kZxqpAsX.jpg',
  'https://r.resimlink.com/reR8F.jpg',
];
