export const aparts = [
  {
    id: 1,
    title: "1+1 Apart",
    description:
      "Dairelerimizde sizlerin rahatı için her şeyi düşündük. Evinizin konforunu aratmayacak bir tatil için tv, sıcak su ve her türlü mutfak araç gereci sizlerin hizmetine sunulmuştur. Avşa merkezde bulunan dairelerimiz Avşa İDO iskelesine 50 metre mesafededir. Ailenizle güvenli ve konforlu bir tatil geçirmek için Avşa Mahir apart tüm sezon boyunca hizmetinizdedir.",
    features: [
      "Uydu Yayını",
      "Denize Yakın",
      "Deniz Manzaralı",
      "İDO İskelesine Yakın",
    ],
    coverImage: "/images/apart-images/apart1/1.jpg",
    images: [
      "/images/apart-images/apart1/1.jpg",
      "/images/apart-images/apart1/2.jpg",
      "/images/apart-images/apart1/3.jpg",
      "/images/apart-images/apart1/4.jpg",
      "/images/apart-images/apart1/10.jpg",
      "/images/apart-images/apart1/5.jpg",
      "/images/apart-images/apart1/6.jpg",
      "/images/apart-images/apart1/7.jpg",
      "/images/apart-images/apart1/8.jpg",
      "/images/apart-images/apart1/9.jpg",
    ],
    capacity: 5,
    size: 90,
    breakfast: false,
    terace: true,
    slug: "apart-1",
  },
  {
    id: 2,
    title: "1+1 Apart",
    description:
      "Dairelerimizde sizlerin rahatı için her şeyi düşündük. Evinizin konforunu aratmayacak bir tatil için tv, sıcak su ve her türlü mutfak araç gereci sizlerin hizmetine sunulmuştur. Avşa merkezde bulunan dairelerimiz Avşa İDO iskelesine 50 metre mesafededir. Ailenizle güvenli ve konforlu bir tatil geçirmek için Avşa Mahir apart tüm sezon boyunca hizmetinizdedir.",
    features: [
      "Uydu Yayını",
      "Denize Yakın",
      "Deniz Manzaralı",
      "İDO İskelesine Yakın",
    ],
    coverImage: "/images/apart-images/apart2/1.jpg",
    images: [
      "/images/apart-images/apart2/1.jpg",
      "/images/apart-images/apart2/2.jpg",
      "/images/apart-images/apart2/3.jpg",
      "/images/apart-images/apart2/4.jpg",
      "/images/apart-images/apart2/5.jpg",
      "/images/apart-images/apart2/6.jpg",
      "/images/apart-images/apart2/7.jpg",
      "/images/apart-images/apart2/8.jpg",
      "/images/apart-images/apart2/video.mp4",
    ],
    capacity: 5,
    size: 75,
    breakfast: false,
    terace: true,
    slug: "apart-2",
  },
  {
    id: 3,
    title: "1+1 Apart",
    description:
      "Dairelerimizde sizlerin rahatı için her şeyi düşündük. Evinizin konforunu aratmayacak bir tatil için tv, sıcak su ve her türlü mutfak araç gereci sizlerin hizmetine sunulmuştur. Avşa merkezde bulunan dairelerimiz Avşa İDO iskelesine 50 metre mesafededir. Ailenizle güvenli ve konforlu bir tatil geçirmek için Avşa Mahir apart tüm sezon boyunca hizmetinizdedir.",

    features: [
      "Uydu Yayını",
      "Denize Yakın",
      "Deniz Manzaralı",
      "İDO İskelesine Yakın",
    ],
    coverImage: "/images/apart-images/apart3/1.jpg",
    images: [
      "/images/apart-images/apart3/1.jpg",
      "/images/apart-images/apart3/2.jpg",
      "/images/apart-images/apart3/3.jpg",
      "/images/apart-images/apart3/4.jpg",
      "/images/apart-images/apart3/5.jpg",
      "/images/apart-images/apart3/6.jpg",
      "/images/apart-images/apart3/7.jpg",
    ],
    capacity: 5,
    size: 50,
    breakfast: false,
    terace: false,
    slug: "apart-3",
  },
];

export const gallery = [
  "/images/apart-images/apart1/1.jpg",
  "/images/apart-images/apart1/2.jpg",
  "/images/apart-images/apart1/3.jpg",
  "/images/apart-images/apart1/4.jpg",
  "/images/apart-images/apart1/10.jpg",
  "/images/apart-images/apart1/5.jpg",
  "/images/apart-images/apart1/6.jpg",
  "/images/apart-images/apart1/7.jpg",
  "/images/apart-images/apart1/8.jpg",
  "/images/apart-images/apart1/9.jpg",
  "/images/apart-images/apart2/1.jpg",
  "/images/apart-images/apart2/2.jpg",
  "/images/apart-images/apart2/3.jpg",
  "/images/apart-images/apart2/4.jpg",
  "/images/apart-images/apart2/5.jpg",
  "/images/apart-images/apart2/6.jpg",
  "/images/apart-images/apart2/7.jpg",
  "/images/apart-images/apart2/8.jpg",
  "/images/apart-images/apart3/1.jpg",
  "/images/apart-images/apart3/2.jpg",
  "/images/apart-images/apart3/3.jpg",
  "/images/apart-images/apart3/4.jpg",
  "/images/apart-images/apart3/5.jpg",
  "/images/apart-images/apart3/6.jpg",
  "/images/apart-images/apart3/7.jpg",
  "/images/apart-images/apart3/8.jpg",
];
